version: '3.9'
services: 
    web:
        build: .
        ports: 
          - 4000:3000
        environment: 
            PORT: 3000
            MONGODB_URL: 'mongodb://db:27017'
        depends_on: 
          - db
        volumes: 
          - .:/app
          - /app/node_modules/
    db:
        image: 'mongo'
        ports: 
          - "27017:27017"
        volumes: 
          - ./data:/data/db
